---
# This playbook installs apache2 server

- name: Apache | Installs Apache2 server
  action: apt pkg={{ item }} state=installed
  tags: apache2
  with_items:
    - apache2

- name: Apache | Enable virtual hosts, rewrite
  action: command a2enmod rewrite vhost_alias proxy proxy_http
  tags: apache2

- name: Check exists host configurations
  stat: path=/etc/apache2/sites-available/05-web.conf
  register: hosts_dir

- name: Add vhost symlink in sites-enabled (web)
  template: src=vhost.conf.tpl dest=/etc/apache2/sites-available/05-web.conf mode=755
  when: not hosts_dir.stat.exists
  tags: app

- name: Enable our new site (web)
  action: command a2ensite 05-web
  when: not hosts_dir.stat.exists
  become: yes
  become_method: sudo
  tags: app

- name: Restart Apache
  action: service name=apache2 state=restarted
  when: not hosts_dir.stat.exists
  tags: app