---
# This playbook installs development environment

- name: add php 5.6 repository entry
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present

- name: PHP | Installs php development tools
  action: apt pkg={{ item }} state=installed
  with_items: 
    - php5
    - php-apc
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - imagemagick
    - php5-imagick
    - php5-cli
    - php-pear
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-xdebug
    - php5-imap
    - php5-mysql
    - php5-dev
    - php5-ldap
    - php5-sqlite
    - php5-memcached
    - php5-mysql
    - php-codesniffer

- name: PHP | Configuration Apache
  ini_file: dest=/etc/php5/apache2/php.ini section=Date option=date.timezone value={{server.timezone}}
  become: yes
  become_method: sudo

- name: PHP | Configuration Client
  ini_file: dest=/etc/php5/cli/php.ini section=Date option=date.timezone value={{server.timezone}}
  become: yes
  become_method: sudo

- name: PHP | Configuration file, php.ini
  action: template src=etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
  tags: common

- name: PHP | Download Composer installer
  get_url: url=https://getcomposer.org/installer dest=/tmp/composer-setup.php mode=a+x

- name: PHP | Run Composer installer
  command: php composer-setup.php --filename=composer --install-dir=/usr/local/bin chdir=/tmp

- name: PHP | Install Symfony
  command: curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony

- name: PHP | Make symfony installer executable
  file: path=/usr/local/bin/symfony mode=a+x

- name: PHP | Creates adminer directory
  file: path={{ project_dir }}/adminer state=directory mode=755

- name: PHP | Install adminer
  get_url: url=https://www.adminer.org/latest-mysql-en.php dest={{ project_dir }}/adminer/index.php mode=a+x

- name: Restart Apache
  action: service name=apache2 state=restarted