- name: Check elasticsearch installed
  stat: path=/etc/init.d/elasticsearch
  register: elasticsearch_dir

- name: Install key
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  when: not elasticsearch_dir.stat.exists
  tags: elasticsearch

- name: Add repository
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' state=present
  when: not elasticsearch_dir.stat.exists
  tags: elasticsearch

- name: Install package
  apt: name=elasticsearch state=present update_cache=yes
  when: not elasticsearch_dir.stat.exists
  tags: elasticsearch

- name: Configuration
  copy: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml mode=755
  when: not elasticsearch_dir.stat.exists
  tags: elasticsearch

- name: Install ElasticHQ plugin
  command: /usr/share/elasticsearch/bin/plugin --install royrusso/elasticsearch-HQ
  args:
    chdir: /usr/share/elasticsearch
    creates: /usr/share/elasticsearch/plugins/HQ
  when: not elasticsearch_dir.stat.exists
  tags: elasticsearch

- name: Start service
  service: name=elasticsearch state=started enabled=yes
  tags: elasticsearch