---
- name: add mysql repository
  apt_repository: repo="ppa:ondrej/mysql-5.6" state=present
  tags: mysql

- name: Install mysql
  action: apt pkg={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
  notify:
    - restart mysql
  tags: mysql

- name: Start the MySQL service
  action: service name=mysql state=started
  tags: mysql

# 'localhost' needs to be the last item for idempotency , see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user: name={{ dbuser }} host={{ item }} password={{ dbpass }} priv=*.*:ALL,GRANT
  with_items:
    - 10.0.%.%
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: mysql

- name: insert timezones in mysql
  shell: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u{{ dbuser }} -p{{ dbpass }} --force mysql
  ignore_errors: yes
  tags: mysql